-- CogniPulse Supabase Database Schema
-- Paste and run this script in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

CREATE TABLE IF NOT EXISTS agents (
  agent_id TEXT PRIMARY KEY,
  persona_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  next_run_at TEXT
);

CREATE TABLE IF NOT EXISTS posts (
  id TEXT PRIMARY KEY,
  agent_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  text TEXT NOT NULL,
  rationale TEXT NOT NULL,
  sources_json TEXT NOT NULL,
  topic_key TEXT NOT NULL,
  embedding_json TEXT
);

CREATE TABLE IF NOT EXISTS topic_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id TEXT NOT NULL,
  reviewed_at TEXT NOT NULL,
  candidate_title TEXT,
  candidate_url TEXT,
  verdict TEXT NOT NULL,
  reason TEXT,
  novelty_score REAL,
  relevance_score REAL
);

CREATE TABLE IF NOT EXISTS run_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  outcome TEXT,
  detail TEXT
);

-- Enable Row Level Security (RLS) with open public access policies
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE run_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read agents" ON agents;
DROP POLICY IF EXISTS "Allow public write agents" ON agents;
CREATE POLICY "Allow public read agents" ON agents FOR SELECT USING (true);
CREATE POLICY "Allow public write agents" ON agents FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public read posts" ON posts;
DROP POLICY IF EXISTS "Allow public write posts" ON posts;
CREATE POLICY "Allow public read posts" ON posts FOR SELECT USING (true);
CREATE POLICY "Allow public write posts" ON posts FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public read topic_reviews" ON topic_reviews;
DROP POLICY IF EXISTS "Allow public write topic_reviews" ON topic_reviews;
CREATE POLICY "Allow public read topic_reviews" ON topic_reviews FOR SELECT USING (true);
CREATE POLICY "Allow public write topic_reviews" ON topic_reviews FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public read run_log" ON run_log;
DROP POLICY IF EXISTS "Allow public write run_log" ON run_log;
CREATE POLICY "Allow public read run_log" ON run_log FOR SELECT USING (true);
CREATE POLICY "Allow public write run_log" ON run_log FOR ALL USING (true);
